services:
  - type: web
    name: who-what-where-when-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 4000

  - type: web
    name: who-what-where-when-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    
